version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      # for backwards compatibility with older vscode versions
      - dependency-name: "@types/node"
      - dependency-name: "@types/vscode"
